version: '2'
services:
  tafxtrade-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/tafxtrade/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tafxtrade
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
